name: Main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: 📚 Main
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: 👀 Lint
        run: npm run lint

      - name: 🚀 Build
        run: npm run build
